### ISSUE TITLE
ClassNotFoundException on activity creation

### ISSUE THREAD

**Issue by Cypaubr** [DevLight-Mobile-Agency/NavigationTabStrip#9]
I imported the library by using Gralde Maven Central. I got no problem when I sync the projet and when I build the app but when I run it on my second activity (where the NavigationTabStrip is used) it crashes.

Here is the stacktrace :

```
06-23 21:38:27.792 29422-29422/com.linkpulsion.nethernalvibes E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.linkpulsion.nethernalvibes, PID: 29422
                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.linkpulsion.nethernalvibes/com.linkpulsion.nethernalvibes.Player}: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class com.gigamole.library.NavigationTabStrip
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
                                                                                    at android.app.ActivityThread.access$1100(ActivityThread.java:221)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:158)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                                 Caused by: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class com.gigamole.library.NavigationTabStrip
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
                                                                                    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                    at com.linkpulsion.nethernalvibes.Player.onCreate(Player.java:29)
                                                                                    at android.app.Activity.performCreate(Activity.java:6876)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                                    at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:158) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                                 Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class com.gigamole.library.NavigationTabStrip
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
                                                                                    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                                    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                    at com.linkpulsion.nethernalvibes.Player.onCreate(Player.java:29) 
                                                                                    at android.app.Activity.performCreate(Activity.java:6876) 
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                                    at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:158) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                                 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.gigamole.library.NavigationTabStrip" on path: DexPathList[[zip file "/data/app/com.linkpulsion.nethernalvibes-1/base.apk"],nativeLibraryDirectories=[/data/app/com.linkpulsion.nethernalvibes-1/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:595)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                                    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                                    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                    at com.linkpulsion.nethernalvibes.Player.onCreate(Player.java:29) 
                                                                                    at android.app.Activity.performCreate(Activity.java:6876) 
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                                    at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:158) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                                    Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.gigamole.library.NavigationTabStrip" on path: DexPathList[[dex file "/data/data/com.linkpulsion.nethernalvibes/files/instant-run/dex/slice-support-annotations-23.4.0_a6bb2a5bb9a40e4d6f6829e6518129a51f2ebb3b-classes.dex", dex file "/data/data/com.linkpulsion.nethernalvibes/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.linkpulsion.nethernalvibes/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.linkpulsion.nethernalvibes/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.linkpulsion.nethernalvibes/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.linkpulsion.nethernalvibes/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.linkpulsion.nethernalvibes/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.linkpulsion.nethernalvibes/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.linkpulsion.nethernalvibes
06-23 21:38:27.792 29422-29422/com.linkpulsion.nethernalvibes D/Error: ERR: exClass=java.lang.ClassNotFoundException
06-23 21:38:27.792 29422-29422/com.linkpulsion.nethernalvibes D/Error: ERR: exMsg=Didn't find class "com.gigamole.library.NavigationTabStrip" on path: DexPathList[[zip file "/data/app/com.linkpulsion.nethernalvibes-1/base.apk"],nativeLibraryDirectories=[/data/app/com.linkpulsion.nethernalvibes-1/lib/arm64, /vendor/lib64, /system/lib64]]
06-23 21:38:27.792 29422-29422/com.linkpulsion.nethernalvibes D/Error: ERR: file=BaseDexClassLoader.java
06-23 21:38:27.792 29422-29422/com.linkpulsion.nethernalvibes D/Error: ERR: class=dalvik.system.BaseDexClassLoader
06-23 21:38:27.792 29422-29422/com.linkpulsion.nethernalvibes D/Error: ERR: method=findClass line=56
```

**Comment by GIGAMOLE** [comment]
Hello. Wait for fix.

**Comment by GIGAMOLE** [comment]
Fixed.
